TrelloClone/Controllers/DoController.cs
using InstagramApiSharp.API;
using InstagramApiSharp.Classes;
using InstagramApiSharp.Classes.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using WebApplication12.Models;

namespace WebApplication12.Controllers
{
    public class DoController : Controller
    {
        private ToDoDatabaseEntities _db = new ToDoDatabaseEntities();

        #region Index

        // GET: ToDo
        public ActionResult Index()
        {
            if (Session["LoginUser"] is User userLogin)
            {
                List<ToDo> todoList = _db.ToDo.Where(x => x.User.Userid == userLogin.Userid).ToList();
                return View(todoList);

            }

            return RedirectToAction("Login", "Account");
        }

        #endregion

        #region Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Description")] ToDo toDo)
        {
            var userLogin = Session["LoginUser"] as User;

            if (ModelState.IsValid)
            {
                toDo.Userid = userLogin.Userid;
                toDo.IsActive = 0;
                toDo.Statusid = 1;
                if (Request.Files.Count > 0)
                {
                    string fileName = Path.GetFileName(Request.Files[0].FileName);
                    string ext = Path.GetExtension(Request.Files[0].FileName);
                    string path = "~/images/" + fileName + ext;
                    Request.Files[0].SaveAs(Server.MapPath(path));
                    toDo.Image = "/images/" + fileName + ext;
                }

                _db.ToDo.Add(toDo);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Login", "Account");
        }

        #endregion

        #region statusChange

        public ActionResult StatusChange(int id)
        {
            var data = _db.ToDo.SingleOrDefault(x => x.Id == id);
            if (data != null)
            {
                switch (data.Statusid)
                {
                    case 1:
                        data.Statusid = 2;
                        break;
                    case 2:
                        data.Statusid = 3;
                        break;
                    default:
                        data.Statusid = 1;
                        break;
                }

                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return Json("hata", JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Delete
        public ActionResult Delete(int id)
        {

            var data = _db.ToDo.SingleOrDefault(x => x.Id == id);
            if (data != null)
            {
                switch (data.Statusid)
                {
                    case 3:
                        data.IsActive = 1;
                        break;
                    default:
                        data.IsActive = 0;
                        break;
                }

                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            return Json("hata", JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Trash

        public ActionResult Trash()
        {
            var userLogin = Session["LoginUser"] as User;
            List<ToDo> todoList = _db.ToDo.Where(x => x.User.Userid == userLogin.Userid).ToList();
            return View(todoList);
        }

        #endregion

        #region Edit
        public ActionResult Edit(int id)
        {
            var data = _db.ToDo.SingleOrDefault(x => x.Id == id);
            if (data == null)
            {
                return HttpNotFound();
            }
            ViewBag.StatusId = new SelectList(_db.Status, "Statusid", "Name", data.Statusid);
            ViewBag.Userid = new SelectList(_db.User, "Userid", "NameSurname", data.Userid);
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(ToDo toDo)
        {
            ViewBag.StatusId = new SelectList(_db.Status, "Statusid", "Name", toDo.Statusid);
            ViewBag.Userid = new SelectList(_db.User, "Userid", "NameSurname", toDo.Userid);
            var loginuser = Session["LoginUser"] as User;
            toDo.Userid = loginuser.Userid;
            _db.Entry(toDo).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion
    }
}

TrelloClone/Views/Do/Create.cshtml
@model  WebApplication12.Models.ToDo
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "Do", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        @Html.ValidationSummary(true)

        <div class="form-group">
            <h5 class="control-label col-md-2">Başlık</h5>
            <div class="col-md-5">
                @Html.EditorFor(todo => todo.Title)
                @Html.ValidationMessageFor(todo => todo.Title)
            </div>
        </div>

        <div class="form-group">
            <h5 class="control-label col-md-2">Açıklama</h5>
            <div class="col-md-5">
                @Html.EditorFor(todo => todo.Description)
                @Html.ValidationMessageFor(todo => todo.Description)
            </div>
        </div>

        <div class="form-group">
            <h5 class="control-label col-md-2">Resim</h5>
            <div class="col-md-5">
                <input type="file" name="Resim" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" id="btnsave" />
            </div>
        </div>
    </div>

    <script>
        $('#btnsave').click(function () {
            ({
                title: "Wow!",
                text: "Message!",
                type: "success"
            }),
                function () {
                    window.location.href = '/Do/Index';
                }
        });
    </script>

}

TrelloClone/Views/Do/Delete.cshtml
@model  WebApplication12.Models.ToDo
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
E<div>

    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
        <dd>@Html.DisplayFor(model => model.Id)</dd>
        <dt>@Html.DisplayNameFor(model => model.Title)</dt>
        <dd>@Html.DisplayFor(model => model.Title)</dd>
        <dt>@Html.DisplayNameFor(model => model.Description)</dt>
        <dd>@Html.DisplayFor(model => model.Description)</dd>
    </dl>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

TrelloClone/Views/Do/Edit.cshtml
@model WebApplication12.Models.ToDo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Do", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2 class="text-center">Düzenle</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Image)

        <div class="form-group">
            <h5 class="control-label col-md-2">Başlık</h5>
            <div class="col-md-3">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h5 class="control-label col-md-2">Açıklama</h5>
            <div class="col-md-3">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h5 class="control-label col-md-2">Durum</h5>
            <div class="col-md-3">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Statusid, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-8">
                <input type="submit" value="Kaydet" class="btn btn-success" />
                <a href="/Do/Index"><button type="button" class="btn btn-danger">Geri Dön</button></a>
            </div>
        </div>
    </div>
}

TrelloClone/Views/Do/Index.cshtml
@model  List<WebApplication12.Models.ToDo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    $(function () {
        $(".draggable").draggable({
            revert: "invalid"
        });
        $('.column').droppable({
            accept: '.draggable',
            drop: function (event, ui) {
                var dropped = ui.draggable;
                var droppedOn = $(this);
                $(dropped).detach().css({ top: 0, left: 0 }).appendTo(droppedOn);
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json",
                    url: "",
                    beforeSend: function (request) {
                        request.setRequestHeader("RequestVerificationToken", $('#RequestVerificationToken').val());
                    },
                    data: JSON.stringify({ cardId: dropped[0].id, columnId: droppedOn[0].id }),
                });
            }
        });
    });
</script>


<div class="container">
    <div class="row">
        <div class="col-md-12 ">
            <a href="/Do/Create"><button type="button" class="btn btn-success">Ekle</button></a>
            <a href="/Do/Trash"><button type="button" class="btn right btn-danger">Çöp Kutusu</button></a>
        </div>
    </div>

    <div class="row">
        <div class="col m4">
            <div class="column" style="min-height: 600px">
                <h3 style="text-align:center">Yapılacaklar</h3>
                @foreach (var column in Model.Where(x => x.Statusid == 1 && x.IsActive == 0))
                {

                    if (column.Image != null)
                    {
                        <div class="thumbnail draggable">
                            <div class="caption draggable">
                                <img src="@column.Image" width="350" height="200" alt="" />
                                <h3>@column.Title</h3>
                                <p>@column.Description</p>
                                <p>
                                    <a href="/Do/StatusChange/@column.Id" class="btn btn-primary" role="button">Sonraki</a>
                                    <a href="/Do/Edit/@column.Id" class="btn btn-default" role="button">Düzenle</a>
                                </p>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="thumbnail">
                            <div class="caption">
                                <img src="~/images/Adsız.png" width="350" height="200" alt="" />
                                <h3>@column.Title</h3>
                                <p>@column.Description</p>
                                <p>
                                    <a href="/Do/StatusChange/@column.Id" class="btn btn-primary" role="button">Sonraki</a>
                                    <a href="/Do/Edit/@column.Id" class="btn btn-default" role="button">Düzenle</a>
                                </p>
                            </div>
                        </div>
                    }



                }

            </div>
        </div>
        <div class="col m4">
            <div class="column" style="min-height: 600px">
                <h3 style="text-align:center">Yapılanlar</h3>
                @foreach (var column in Model.Where(x => x.Statusid == 2 && x.IsActive == 0))
                {
                    if (column.Image != null)
                    {
                        <div class="thumbnail">
                            <div class="caption">
                                <img src="@column.Image" width="350" height="200" alt="" />
                                <h3>@column.Title</h3>
                                <p>@column.Description</p>
                                <p>
                                    <a href="/Do/StatusChange/@column.Id" class="btn btn-primary" role="button">Sonraki</a>
                                    <a href="/Do/Edit/@column.Id" class="btn btn-default" role="button">Düzenle</a>
                                </p>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="thumbnail">
                            <div class="caption">
                                <img src="~/images/Adsız.png" width="350" height="200" alt="" />
                                <h3>@column.Title</h3>
                                <p>@column.Description</p>
                                <p>
                                    <a href="/Do/StatusChange/@column.Id" class="btn btn-primary" role="button">Sonraki</a>
                                    <a href="/Do/Edit/@column.Id" class="btn btn-default" role="button">Düzenle</a>
                                </p>
                            </div>
                        </div>
                    }

                }

            </div>
        </div>
        <div class="col m4">
            <div class="column" style="min-height: 600px">
                <h3 style="text-align:center">Tamamlandı</h3>
                @foreach (var column in Model.Where(x => x.Statusid == 3 && x.IsActive == 0))

                {
                    if (column.Image != null)
                    {
                        <div class="thumbnail">
                            <div class="caption">
                                <img src="@column.Image" width="350" height="200" alt="" />
                                <h3>@column.Title</h3>
                                <p>@column.Description</p>
                                <p><a href="/Do/Delete/@column.Id" class="btn btn-primary" role="button">Sil</a> <a href="/Do/Edit/@column.Id" class="btn btn-default" role="button">Düzenle</a></p>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="thumbnail">
                            <div class="caption">
                                <img src="~/images/Adsız.png" width="350" height="200" alt="" />
                                <h3>@column.Title</h3>
                                <p>@column.Description</p>
                                <p><a href="/Do/Delete/@column.Id" class="btn btn-primary" role="button">Sil</a> <a href="/Do/Edit/@column.Id" class="btn btn-default" role="button">Düzenle</a></p>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

TrelloClone/Views/Do/Trash.cshtml
@model IEnumerable<WebApplication12.Models.ToDo>
@{
    ViewBag.Title = "Trash";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3 style="text-align:center">Çöp Kutusu</h3>
    <div class="row">
        @foreach (var column in Model.Where(x => x.IsActive == 1))
        {

            if (column.Image != null)
            {
                <div class="thumbnail">
                    <div class="caption">
                        <img src="@column.Image" alt="" />
                        <h3>@column.Title</h3>
                        <p>@column.Description</p>
                        <p>
                            <a href="/Do/Delete/@column.Id" class="btn btn-primary" role="button">Button</a>
                            <a href="/Do/Delete/@column.Id" class="btn btn-default" role="button">Button</a>
                        </p>
                    </div>
                </div>
            }
            else
            {
                <div class="thumbnail">
                    <div class="caption">
                        <img src="~/images/Adsız.png" alt="" />
                        <h3>@column.Title</h3>
                        <p>@column.Description</p>
                        <p>
                            <a href="/Do/Delete/@column.Id" class="btn btn-primary" role="button">Button</a>
                            <a href="/Do/Delete/@column.Id" class="btn btn-default" role="button">Button</a>
                        </p>
                    </div>
                </div>
            }


            @*<div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="~/assets/Adsız.png" alt="...">
                        <div class="caption">
                            <h3>@column.Title</h3>
                            <p>@column.Description</p>
                            <p><a href="/Do/Delete/@column.Id" class="btn btn-primary" role="button">Button</a>
                                <a href="/Do/Delete/@column.Id" class="btn btn-default" role="button">Button</a></p>
                        </div>
                    </div>

                </div>*@
        }
    </div>
</div>

TrelloClone/Views/Do/Update.cshtml
@model  WebApplication12.Models.ToDo

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}